export const TASK_ACTIVITY_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  TITLE_CHANGED: 'TITLE_CHANGED',
  DESCRIPTION_CHANGED: 'DESCRIPTION_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COLUMN_CHANGED: 'COLUMN_CHANGED',
  SPRINT_CHANGED: 'SPRINT_CHANGED',
  ASSIGNEE_CHANGED: 'ASSIGNEE_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  TYPE_CHANGED: 'TYPE_CHANGED',
  STORY_POINTS_CHANGED: 'STORY_POINTS_CHANGED',
  DUE_DATE_CHANGED: 'DUE_DATE_CHANGED',
  RANK_CHANGED: 'RANK_CHANGED',
  TASK_ARCHIVED: 'TASK_ARCHIVED',
  TASK_RESTORED: 'TASK_RESTORED',
  TASK_PERMANENTLY_DELETED: 'TASK_PERMANENTLY_DELETED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',
  COMMENT_DELETED: 'COMMENT_DELETED',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',
  LABELS_CHANGED: 'LABELS_CHANGED',
  COVER_CHANGED: 'COVER_CHANGED',
  WORK_LOGGED: 'WORK_LOGGED',
} as const;

export type TaskActivityType =
  (typeof TASK_ACTIVITY_TYPES)[keyof typeof TASK_ACTIVITY_TYPES];

export const TASK_ACTIVITY_TYPE_VALUES = Object.values(TASK_ACTIVITY_TYPES);
