export const MAX_ATTACHMENT_SIZE = 10 * 1024 * 1024;

export const BLOCKED_ATTACHMENT_EXTENSIONS = new Set([
  '.ade',
  '.adp',
  '.app',
  '.apk',
  '.bat',
  '.bin',
  '.cmd',
  '.com',
  '.cpl',
  '.dll',
  '.dmg',
  '.exe',
  '.gadget',
  '.hta',
  '.ins',
  '.iso',
  '.jar',
  '.js',
  '.jse',
  '.lib',
  '.lnk',
  '.msi',
  '.msp',
  '.mst',
  '.pif',
  '.ps1',
  '.scr',
  '.sh',
  '.sys',
  '.vb',
  '.vbe',
  '.vbs',
  '.ws',
  '.wsf',
]);

export const ALLOWED_ATTACHMENT_EXTENSIONS = new Set([
  '.csv',
  '.doc',
  '.docx',
  '.gif',
  '.jpeg',
  '.jpg',
  '.json',
  '.md',
  '.mp4',
  '.pdf',
  '.png',
  '.ppt',
  '.pptx',
  '.rtf',
  '.svg',
  '.txt',
  '.webp',
  '.xls',
  '.xlsx',
  '.zip',
]);

export const ALLOWED_ATTACHMENT_MIME_TYPES = new Set([
  'application/json',
  'application/msword',
  'application/pdf',
  'application/rtf',
  'application/vnd.ms-excel',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/zip',
  'image/gif',
  'image/jpeg',
  'image/png',
  'image/svg+xml',
  'image/webp',
  'text/csv',
  'text/markdown',
  'text/plain',
  'video/mp4',
]);

export const ADDITIONAL_ATTACHMENT_MIME_TYPES_BY_EXTENSION = new Map([
  [
    '.mp4',
    new Set(['application/mp4', 'application/octet-stream', 'video/x-m4v']),
  ],
]);
