export const AUTH_AUDIT_EVENTS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  REFRESH_FAILED: 'REFRESH_FAILED',
  REFRESH_REUSED: 'REFRESH_REUSED',
  TOKEN_FAMILY_REVOKED: 'TOKEN_FAMILY_REVOKED',
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_FAILED: 'GOOGLE_LOGIN_FAILED',
  EMAIL_VERIFICATION_SUCCESS: 'EMAIL_VERIFICATION_SUCCESS',
  EMAIL_VERIFICATION_FAILED: 'EMAIL_VERIFICATION_FAILED',
  EMAIL_VERIFICATION_RESENT: 'EMAIL_VERIFICATION_RESENT',
  EMAIL_VERIFICATION_RESEND_FAILED: 'EMAIL_VERIFICATION_RESEND_FAILED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_VERIFIED_GRANT_ISSUED: 'OTP_VERIFIED_GRANT_ISSUED',
  OTP_FAILED: 'OTP_FAILED',
  OTP_VERIFY_FAILED: 'OTP_VERIFY_FAILED',
  RATE_LIMIT_HIT: 'RATE_LIMIT_HIT',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
} as const;

export type AuthAuditEventLiteral =
  (typeof AUTH_AUDIT_EVENTS)[keyof typeof AUTH_AUDIT_EVENTS];
