export const TASK_AUDIT_EVENTS = {
  TASK_LIST_VIEWED: 'TASK_LIST_VIEWED',
  TASK_FILTER_APPLIED: 'TASK_FILTER_APPLIED',
  TASK_FILTER_FAILED: 'TASK_FILTER_FAILED',
  TASK_VIEWED: 'TASK_VIEWED',
  TASK_CREATE_SUCCESS: 'TASK_CREATE_SUCCESS',
  TASK_CREATE_FAILED: 'TASK_CREATE_FAILED',
  TASK_UPDATE_SUCCESS: 'TASK_UPDATE_SUCCESS',
  TASK_UPDATE_FAILED: 'TASK_UPDATE_FAILED',
  TASK_MOVE_SUCCESS: 'TASK_MOVE_SUCCESS',
  TASK_MOVE_FAILED: 'TASK_MOVE_FAILED',
  TASK_DELETE_SUCCESS: 'TASK_DELETE_SUCCESS',
  TASK_DELETE_FAILED: 'TASK_DELETE_FAILED',
  TASK_ARCHIVE_SUCCESS: 'TASK_ARCHIVE_SUCCESS',
  TASK_ARCHIVE_FAILED: 'TASK_ARCHIVE_FAILED',
  TASK_RESTORE_SUCCESS: 'TASK_RESTORE_SUCCESS',
  TASK_RESTORE_FAILED: 'TASK_RESTORE_FAILED',
  TASK_DELETE_PERMANENT_SUCCESS: 'TASK_DELETE_PERMANENT_SUCCESS',
  TASK_DELETE_PERMANENT_FAILED: 'TASK_DELETE_PERMANENT_FAILED',
  TASK_ATTACHMENT_DOWNLOADED: 'TASK_ATTACHMENT_DOWNLOADED',
  TASK_ATTACHMENT_PREVIEWED: 'TASK_ATTACHMENT_PREVIEWED',
} as const;

export type TaskAuditEventLiteral =
  (typeof TASK_AUDIT_EVENTS)[keyof typeof TASK_AUDIT_EVENTS];
