// /src/config/apiRoutes.ts

export const apiRoutes = {
    FOR_YOU: '/for-you',
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        LOGOUT: '/auth/logout',
        ME: '/auth/me',
        MY_PERMISSIONS: '/auth/my-permissions',
        ACCOUNTS: '/auth/accounts',
        ACCOUNTS_SWITCH: '/auth/accounts/switch',
        ACCOUNTS_FORGET: (accountId: string) => `/auth/accounts/${accountId}`,
        ACCOUNTS_RECENT: '/auth/accounts/recent',
        ACCOUNTS_RECENT_FORGET: (accountId: string) => `/auth/accounts/recent/${accountId}`,
        USERS: '/users',
        UPDATE: '/users/profile',
    },
    WORKSPACES: {
        BASE: '/workspaces',
        BY_ID: (workspaceId: string) => `/workspaces/${workspaceId}`,
        UPDATE: (workspaceId: string) => `/workspaces/${workspaceId}`,
        AVATAR_SAMPLES: '/workspaces/avatar-samples',
        MEMBERS: (workspaceId: string) => `/workspaces/${workspaceId}/members`,
        ADD_MEMBER: (workspaceId: string) => `/workspaces/${workspaceId}/members`,
        LEAVE: (workspaceId: string) => `/workspaces/${workspaceId}/members/me`,
        REMOVE_MEMBER: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}`,
        UPDATE_MEMBER: (workspaceId: string, userId: string) => `/workspaces/${workspaceId}/members/${userId}`,
        INVITES: (workspaceId: string) => `/workspaces/${workspaceId}/invites`,
        INVITE_BY_ID: (workspaceId: string, inviteId: string) => `/workspaces/${workspaceId}/invites/${inviteId}`,
        INVITE_LINK: (workspaceId: string) => `/workspaces/${workspaceId}/invites/link`,
        INVITE_BY_TOKEN: (token: string) => `/workspaces/invites/${token}`,
        ACCEPT_INVITE: (token: string) => `/workspaces/invites/${token}/accept`,
        INVITE_DETAIL_BY_ID: (inviteId: string) => `/workspaces/invites/id/${inviteId}`,
        ACCEPT_INVITE_BY_ID: (inviteId: string) => `/workspaces/invites/id/${inviteId}/accept`,
        DECLINE_INVITE_BY_ID: (inviteId: string) => `/workspaces/invites/id/${inviteId}/decline`,
        BOARD: (workspaceId: string) => `/workspaces/${workspaceId}/board`,
        BOARD_COLUMNS: (workspaceId: string) => `/workspaces/${workspaceId}/board/columns`,
        BOARD_COLUMN: (workspaceId: string, columnId: string) => `/workspaces/${workspaceId}/board/columns/${columnId}`,
        BOARD_COLUMN_MOVE: (workspaceId: string, columnId: string) => `/workspaces/${workspaceId}/board/columns/${columnId}/move`,
        SPRINTS: (workspaceId: string) => `/workspaces/${workspaceId}/sprints`,
        SPRINT: (workspaceId: string, sprintId: string) => `/workspaces/${workspaceId}/sprints/${sprintId}`,
        SPRINT_START: (workspaceId: string, sprintId: string) => `/workspaces/${workspaceId}/sprints/${sprintId}/start`,
        SPRINT_COMPLETE: (workspaceId: string, sprintId: string) => `/workspaces/${workspaceId}/sprints/${sprintId}/complete`,
        SPRINT_COMPLETE_PREVIEW: (workspaceId: string, sprintId: string) => `/workspaces/${workspaceId}/sprints/${sprintId}/complete-preview`,
        ACTIVE_SPRINT: (workspaceId: string) => `/workspaces/${workspaceId}/active-sprint`,
        BACKLOG: (workspaceId: string) => `/workspaces/${workspaceId}/backlog`,
        LABELS: (workspaceId: string) => `/workspaces/${workspaceId}/labels`,
        LABEL: (workspaceId: string, labelId: string) => `/workspaces/${workspaceId}/labels/${labelId}`,
    },
    PROJECTS: {
        BASE: '/projects',
        BY_ID: (id: string) => `/projects/${id}`,
        MEMBERS: (id: string) => `/projects/${id}/members`,
        ADD_MEMBER: (id: string) => `/projects/${id}/members`,
        REMOVE_MEMBER: (id: string, userId: string) => `/projects/${id}/members/${userId}`,
        UPDATE_MEMBER: (id: string, userId: string) => `/projects/${id}/members/${userId}`,
    },
    BOARDS: {
        BASE: '/boards',
        BY_ID: (id: string) => `/boards/${id}`,
        COLUMNS: (id: string) => `/boards/${id}/columns`,
    },
    TASKS: {
        // New workspace-scoped board routes (use these for workspace board/backlog)
        BOARD: (workspaceId: string) => `/workspaces/${workspaceId}/board/tasks`,
        BOARD_TASK_BY_KEY: (workspaceId: string, taskKey: string) => `/workspaces/${workspaceId}/board/key/${taskKey}`,
        BOARD_TASK: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}`,
        BOARD_TASK_UPDATE: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}`,
        BOARD_TASK_MOVE: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/move`,
        BOARD_TASK_REORDER: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/reorder`,
        BOARD_TASK_DELETE: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}`,
        BOARD_TASK_ARCHIVE: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/archive`,
        BOARD_TASK_RESTORE: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/restore`,
        BOARD_TASK_ACTIVITIES: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/activities`,
        BOARD_TASK_ATTACHMENTS: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/attachments`,
        BOARD_TASK_ATTACHMENT: (workspaceId: string, taskId: string, attachmentId: string) => `/workspaces/${workspaceId}/board/${taskId}/attachments/${attachmentId}`,
        BOARD_TASK_ATTACHMENT_PREVIEW: (workspaceId: string, taskId: string, attachmentId: string) => `/workspaces/${workspaceId}/board/${taskId}/attachments/${attachmentId}/preview`,
        BOARD_TASK_ATTACHMENT_DOWNLOAD: (workspaceId: string, taskId: string, attachmentId: string) => `/workspaces/${workspaceId}/board/${taskId}/attachments/${attachmentId}/download`,
        BOARD_TASK_COVER: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/cover`,
        BOARD_TASK_LABELS: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/labels`,
        BOARD_ARCHIVES: (workspaceId: string) => `/workspaces/${workspaceId}/board/archives`,
        BOARD_TASK_COMMENTS: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/comments`,
        BOARD_TASK_COMMENT: (workspaceId: string, taskId: string, commentId: string) => `/workspaces/${workspaceId}/board/${taskId}/comments/${commentId}`,
        BOARD_TASK_WORK_LOGS: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board-tasks/${taskId}/work-logs`,
        BOARD_TASK_WORK_LOG_REPORT: (workspaceId: string) => `/workspaces/${workspaceId}/reports/worklogs`,
        BOARD_TASK_WORK_LOG_UPDATE: (workspaceId: string, taskId: string, logId: string) => `/workspaces/${workspaceId}/board-tasks/${taskId}/work-logs/${logId}`,
        BOARD_TASK_WORK_LOG_DELETE: (workspaceId: string, taskId: string, logId: string) => `/workspaces/${workspaceId}/board-tasks/${taskId}/work-logs/${logId}`,
        BOARD_TASK_LINKED_PAGES: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/links/pages`,
        BOARD_TASK_LINK_PAGE: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/links/pages`,
        BOARD_TASK_UNLINK_PAGE: (workspaceId: string, taskId: string, pageId: string) => `/workspaces/${workspaceId}/board/${taskId}/links/pages/${pageId}`,
        BY_SPRINT: (workspaceId: string, sprintId: string) => `/workspaces/${workspaceId}/board/tasks?sprintId=${sprintId}`,
        // Calendar & Timeline views
        CALENDAR: (workspaceId: string) => `/workspaces/${workspaceId}/board/calendar`,
        TIMELINE: (workspaceId: string) => `/workspaces/${workspaceId}/board/timeline`,
        WORKSPACE_DEPENDENCIES: (workspaceId: string) => `/workspaces/${workspaceId}/board/dependencies`,
        TASK_DEPENDENCIES: (workspaceId: string, taskId: string) => `/workspaces/${workspaceId}/board/${taskId}/dependencies`,
        TASK_DEPENDENCY: (workspaceId: string, taskId: string, depId: string) => `/workspaces/${workspaceId}/board/${taskId}/dependencies/${depId}`,
        // Legacy routes — still used by projects/tasks pages, pending migration
        BASE: '/tasks',
        BY_ID: (id: string) => `/tasks/${id}`,
        BY_PROJECT: (projectId: string) => `/tasks/project/${projectId}`,
        MOVE: (id: string) => `/tasks/${id}/move`,
        STATUS: (id: string) => `/tasks/${id}/status`,
        UPDATE: (id: string) => `/tasks/${id}`,
        ASSIGNEE: (userId: string) => `/tasks/assignee/${userId}`,
    },
    SPRINTS: {
        BASE: '/sprints',
        BY_ID: (id: string) => `/sprints/${id}`,
        START: (id: string) => `/sprints/${id}/start`,
        COMPLETE: (id: string) => `/sprints/${id}/complete`,
    },
    WORKFLOWS: {
        BASE: '/workflows',
        BY_ID: (id: string) => `/workflows/${id}`,
        BY_PROJECT: (projectId: string) => `/workflows/project/${projectId}`,
        CREATE_DEFAULT: (projectId: string) => `/workflows/default/${projectId}`,
        TRANSITIONS: (id: string, fromStatus: string) => `/workflows/${id}/transitions/${fromStatus}`,
    },
    COMMENTS: {
        BASE: '/comments',
        BY_ID: (id: string) => `/comments/${id}`,
        BY_TARGET: (targetType: string, targetId: string) => `/comments/target/${targetType}/${targetId}`,
        THREADED: (targetType: string, targetId: string) => `/comments/target/${targetType}/${targetId}/threaded`,
        PARENT: (parentId: string) => `/comments/parent/${parentId}`,
        COUNT: (targetType: string, targetId: string) => `/comments/count/${targetType}/${targetId}`,
        RESOLVE: (id: string) => `/comments/${id}/resolve`,
        UNRESOLVE: (id: string) => `/comments/${id}/unresolve`,
    },
    PAGES: {
        BASE: '/pages',
        BY_ID: (id: string) => `/pages/${id}`,
        BY_SLUG: (slug: string) => `/pages/slug/${slug}`,
        BY_WORKSPACE: (workspaceKey: string) => `/pages/workspace/${workspaceKey}`,
        ROOT_PAGES: (workspaceKey: string) => `/pages/workspace/${workspaceKey}/root`,
        CHILDREN: (id: string) => `/pages/${id}/children`,
        BY_AUTHOR: (authorId: string) => `/pages/author/${authorId}`,
        MOVE: (id: string) => `/pages/${id}/move`,
        LABELS: (id: string) => `/pages/${id}/labels`,
        SYNC: (id: string) => `/pages/${id}/sync`,
        VERSIONS: (id: string) => `/pages/${id}/versions`,
        VERSION_BY_ID: (id: string, versionId: string) => `/pages/${id}/versions/${versionId}`,
        VERSION_RESTORE: (id: string, versionId: string) => `/pages/${id}/versions/${versionId}/restore`,
        EXPORT_DOCX: (id: string) => `/pages/${id}/export/docx`,
        IMPORT_DOCX: '/pages/import/docx',
        LINKED_TASKS: (pageId: string) => `/pages/${pageId}/linked-tasks`,
    },
    NOTIFICATIONS: {
        BASE: '/notifications',
        BY_ID: (id: string) => `/notifications/${id}`,
        UNREAD_COUNT: '/notifications/unread-count',
        READ: (id: string) => `/notifications/${id}/read`,
        READ_ALL: '/notifications/read-all',
    },
    DASHBOARD: {
        WORKSPACE: (workspaceId: string) => `/dashboard/workspace/${workspaceId}`,
        WORKSPACE_STATS: (workspaceId: string) => `/dashboard/workspace/${workspaceId}/stats`,
        PROJECT: (projectId: string) => `/dashboard/project/${projectId}`,
        USER: '/dashboard/user/me',
        SPRINT: (sprintId: string) => `/dashboard/sprint/${sprintId}`,
    },
    SEARCH: {
        BASE: '/search',
        GLOBAL: '/search/global',
        TASKS: '/search/tasks',
        PROJECTS: '/search/projects',
        PAGES: '/search/pages',
    },
    ATTACHMENTS: {
        BASE: '/attachments',
        BY_ID: (id: string) => `/attachments/${id}`,
        DOWNLOAD: (id: string) => `/attachments/${id}/download`,
    },
    DOCUMENTS: {
        BASE: '/documents',
        UPLOAD: '/documents/upload',
        CREATE_ONLINE: '/documents/create-online',
        BY_ID: (id: string) => `/documents/${id}`,
        CONTENT: (id: string) => `/documents/${id}/content`,
        VERSIONS: (id: string) => `/documents/${id}/versions`,
        VERSION_RESTORE: (id: string, versionId: string) => `/documents/${id}/versions/${versionId}/restore`,
        EXPORT_DOCX: (id: string) => `/documents/${id}/export/docx`,
        IMPORT_DOCX: '/documents/import/docx',
        ATTACH: (id: string) => `/documents/${id}/attach`,
        DETACH: (id: string) => `/documents/${id}/detach`,
        BY_WORKSPACE: (workspaceId: string) => `/documents/workspace/${workspaceId}`,
        VIEW: (id: string) => `/documents/${id}/view`,
        PREVIEW: (id: string) => `/documents/${id}/preview`,
        DOWNLOAD: (id: string) => `/documents/${id}/download`,
        WORKSPACES: (id: string) => `/documents/${id}/workspaces`,
    },
    USERS: {
        BASE: '/users',
        PROFILE: '/users/profile',
        BY_ID: (id: string) => `/users/${id}`,
        WORKSPACE_MEMBERS: '/workspaces/members',
        ALL: '/users/all',
    },
};

export const API_ROUTES = apiRoutes;
