// ─── Auth ───────────────────────────────────────────────────────────────────
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  LOGIN_RETRY_LATER: 'LOGIN_RETRY_LATER',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
} as const;

// ─── Tasks ──────────────────────────────────────────────────────────────────
export const TASK_ERROR_CODES = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ARCHIVED: 'TASK_ARCHIVED',
  TASK_KEY_CONFLICT: 'TASK_KEY_CONFLICT',
  TASK_WORKSPACE_MISMATCH: 'TASK_WORKSPACE_MISMATCH',
} as const;

// ─── Scrum / Sprint ─────────────────────────────────────────────────────────
export const SPRINT_ERROR_CODES = {
  SPRINT_NOT_FOUND: 'SPRINT_NOT_FOUND',
  SPRINT_INVALID_STATUS: 'SPRINT_INVALID_STATUS',
  ACTIVE_SPRINT_EXISTS: 'ACTIVE_SPRINT_EXISTS',
  SPRINT_TARGET_INVALID: 'SPRINT_TARGET_INVALID',
  INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',
} as const;

// ─── Kanban ──────────────────────────────────────────────────────────────────
export const KANBAN_ERROR_CODES = {
  INVALID_COLUMN_NAME: 'INVALID_COLUMN_NAME',
  DUPLICATE_COLUMN_NAME: 'DUPLICATE_COLUMN_NAME',
} as const;

// ─── Workspace ──────────────────────────────────────────────────────────────
export const WORKSPACE_ERROR_CODES = {
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_MEMBER_NOT_FOUND: 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_KEY_CONFLICT: 'WORKSPACE_KEY_CONFLICT',
  USER_NOT_IN_WORKSPACE: 'USER_NOT_IN_WORKSPACE',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  CANNOT_CHANGE_OWNER_ROLE: 'CANNOT_CHANGE_OWNER_ROLE',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_ACCEPTED: 'INVITE_ACCEPTED',
  INVITE_DECLINED: 'INVITE_DECLINED',
  INVITE_WORKSPACE_MISMATCH: 'INVITE_WORKSPACE_MISMATCH',
  INVITE_UNAVAILABLE: 'INVITE_UNAVAILABLE',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  INVITE_ALREADY_PENDING: 'INVITE_ALREADY_PENDING',
  FRONTEND_URL_NOT_CONFIGURED: 'FRONTEND_URL_NOT_CONFIGURED',
} as const;

// ─── User ───────────────────────────────────────────────────────────────────
export const USER_ERROR_CODES = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_USER_ID: 'INVALID_USER_ID',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',
  PASSWORD_HAS_WHITESPACE: 'PASSWORD_HAS_WHITESPACE',
} as const;

// ─── Generic / Common ──────────────────────────────────────────────────────
export const COMMON_ERROR_CODES = {
  WORKSPACE_CONTEXT_NOT_FOUND: 'WORKSPACE_CONTEXT_NOT_FOUND',
  WORKSPACE_MEMBERSHIP_REQUIRED: 'WORKSPACE_MEMBERSHIP_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = string;
